version: 2
jobs:
  Check:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Requirements
          command: |
            python3 -m venv local
            source local/bin/activate
            pip install --upgrade --requirement requirements.txt

      - save_cache:
          paths:
            - ./local
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # lint and unittest
      - run:
          name: Check
          command: |
            source local/bin/activate
            make lint unittest

  Build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Build
          command: |
            source local/bin/activate
            make upload

  Deploy-Staging:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # deploy staging
      - run:
          name: Deploy Staging
          command: |
            source local/bin/activate
            make deploy ENV=staging

      # test staging
      - run:
          name: Test Staging
          command: |
              make test ENV=staging

  Deploy-Production:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # deploy staging
      - run:
          name: Deploy Production
          command: |
            source local/bin/activate
            make deploy ENV=production

      # test staging
      - run:
          name: Test Production
          command: |
              make test ENV=production

workflows:
  version: 2
  build_and_test:
    jobs:
      - Check
      - Build:
          requires:
            - Check
      - Deploy-Staging:
          requires:
            - Build
      - Deploy-Production:
          requires:
            - Deploy-Staging
